<meta charset="gbk">
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<link rel="stylesheet" type="text/css" href="lib/bootstrap/css/bootstrap.css">    
<link rel="stylesheet" type="text/css" href="stylesheets/theme.css">
<link rel="stylesheet" href="lib/font-awesome/css/font-awesome.css">
<script src="/ppf/js/jquery-1.min.js" type="text/javascript"></script>
<!--[if lt IE 9]>
<script src="http://apps.bdimg.com/libs/html5shiv/3.7/html5shiv.min.js"></script>
<script src="http://apps.bdimg.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

<script src="/ppf/js/jquery.base64.js" type="text/javascript"></script>    
<script src="/ppf/js/runpage.js" type="text/javascript"></script>
<script src="/ppf/js/bskdo.js" type="text/javascript"></script> 
<script src="/ppf/js/fun.js" type="text/javascript"></script>
<script src="/ppf/js/select.js" type="text/javascript"></script>
<script src="js/bskdlg.js" type="text/javascript"></script>

<script src="lib/bootstrap/js/bootstrap.js"></script>
    <style type="text/css">
        #line-chart {
            height:300px;
            width:800px;
            margin: 0px auto;
            margin-top: 1em;
        }
        .brand { font-family: georgia, serif; }
        .brand .first {
            color: #ccc;
            font-style: italic;
        }
        .brand .second {
            color: #fff;
            font-weight: bold;
        }
    </style>