
<a href="#dashboard-menu" class="nav-header" data-toggle="collapse"><i class="icon-dashboard"></i>控制中心</a>
<ul id="dashboard-menu" class="nav nav-list collapse in">
<li><a href="./?t=index">主页</a></li>
<li ><a href="./?t=ppf&htm=1">模样管理</a></li>
<li ><a href="./?t=manager&htm=1">管理员</a></li>
<li ><a href="./?t=ppf_module&htm=1">权限模块</a></li> 
<li ><a href="./?t=test&htm=1">测试页面</a></li>     
</ul>    

<a href="#" class="nav-header" style="display:none;" ><i class="icon-question-sign"></i>Help</a>
<a href="#" class="nav-header" style="display:none;"  ><i class="icon-comment"></i>Faq</a>