<meta charset="gbk">
<link rel="stylesheet" href="/widget/bootstrap/css/bootstrap.min.css">  
<script src="/ppf/js/jquery-2.min.js"></script>     
<script src="/widget/bootstrap/js/bootstrap.min.js"></script>   
<script src="/ppf/js/jquery.base64.js" type="text/javascript"></script>
<script src="/ppf/js/fun.js" type="text/javascript"></script> 
<script src="/ppf/js/frtdo.js" type="text/javascript"></script>
<script src="/ppf/js/select.js" type="text/javascript"></script> 
<script src="/ppf/js/cookies.min.js" type="text/javascript"></script> 
<script src="js/local.js" type="text/javascript"></script>
<script src="/widget/layerv2/layer/layer.js" type="text/javascript"></script>
<style>
.ul1{list-style:none;padding-left:22px;line-height:28px;}
.ul1 a{color:#888;}
</style>